// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace Kasboek.WebApp.Data.Migrations
{
    [DbContext(typeof(KasboekDbContext))]
    [Migration("20180401213007_RekeningEnTransactie")]
    partial class RekeningEnTransactie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kasboek.WebApp.Models.Rekening", b =>
                {
                    b.Property<int>("RekeningId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsEigenRekening");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("RekeningNummer")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("RekeningId");

                    b.ToTable("Rekeningen");
                });

            modelBuilder.Entity("Kasboek.WebApp.Models.Transactie", b =>
                {
                    b.Property<int>("TransactieId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Bedrag");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("date");

                    b.Property<int?>("NaarRekeningId");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int?>("VanRekeningId");

                    b.HasKey("TransactieId");

                    b.HasIndex("NaarRekeningId");

                    b.HasIndex("VanRekeningId");

                    b.ToTable("Transacties");
                });

            modelBuilder.Entity("Kasboek.WebApp.Models.Transactie", b =>
                {
                    b.HasOne("Kasboek.WebApp.Models.Rekening", "NaarRekening")
                        .WithMany("NaarTransacties")
                        .HasForeignKey("NaarRekeningId");

                    b.HasOne("Kasboek.WebApp.Models.Rekening", "VanRekening")
                        .WithMany("VanTransacties")
                        .HasForeignKey("VanRekeningId");
                });
#pragma warning restore 612, 618
        }
    }
}
